name: Publish on NPM
on:
  push:
    branches: 
      - develop
      - master

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check version changes
      uses: EndBug/version-check@v2
      id: check
      with:
        file-name: package.json
        file-url: https://unpkg.com/hexo-matery-url@2.0.1/package.json
        diff-search: true
        static-checking: localIsNew
    - name: Read .nvmrc
      id: node_version
      if: steps.check.outputs.changed == 'true'
      run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV
    - name: Setup Node
      if: steps.check.outputs.changed == 'true'
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install dependencies
      if: steps.check.outputs.changed == 'true'
      run: npm ci
    - name: Publish package to NPM
      if: steps.check.outputs.changed == 'true'
      run: |
        npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
        npm publish
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
